print("Detta program låter användaren välja två tal som sedan divideras med varandra.")
print()
tal_1 = int(input("Välj tal nummer ett: "))
print(tal_1)
print()
tal_2 = int(input("Välj tal nummer två: "))
print(tal_2)
print()
print("Resultat:")
print(tal_1 / tal_2)
print(tal_1 // tal_2)
